Update index.md
DFE-Digital/architecture pull request #49
Opened 2022-02-07 11:19 UTC by Mazza76

Inclusion of Cloudmersive updates to Dynamics CRM

2022-02-07 11:21 UTC, luke-slowen commented on common-components/index.md
> +-	Implentation approach - Education ICT Advisor - [James Hatch](https://eur.delve.office.com/?u=b67c2ba4-4366-463a-a70c-55fa78872d5b&v=work)
Might be better to find a mailbox for implementation advice?

2022-02-07 11:21 UTC, luke-slowen commented on common-components/index.md
> +-	Product information - Architecture Profession [Architecture Profession](mailto:architecture.profession@education.gov.uk)
Might need a handover with the profession team?

2022-02-07 11:21 UTC, luke-slowen requested changes
Could you address the in-line comment please?

2022-02-07 14:29 UTC, Mazza76 reviewed
Changes made as requested

2022-02-08 15:54 UTC, luke-slowen approved these changes
Added a couple of minor text tweaks

2022-02-08 16:04 UTC, merged